spring:
    application:
        name: apbd-service
        
server:
    port: 8302
    
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka
    instance:
        hostnmae: localhost
